name: Docker Build
on: [push]
jobs:
  build:
    # if: contains(github.ref, 'refs/tags/v')
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - id: docker_build
        uses: jerray/publish-docker-action@v1.0.5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # registry: docker.pkg.github.com
          repository: ${{ secrets.DOCKER_ORGANIZATION }}/hello-api-go
          allow_pull_request: true
          file: Dockerfile
          build_args: version=${{ steps.get_version.outputs.VERSION }}
          auto_tag: true
      - name: Docker Build Report
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            Docker image available at https://hub.docker.com/r/${{ secrets.DOCKER_ORGANIZATION }}/hello-api-go

            Image Name: `${{ steps.docker_build.outputs.tag }}`

            Use `docker run --rm ${{ steps.docker_build.outputs.tag }}` to run it
            
          check_for_duplicate_msg: true  # OPTIONAL
      - name: Create GitHub Release # only if this is on a tag
        if: contains(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
          body: |
            Docker image available at https://hub.docker.com/r/${{ secrets.DOCKER_ORGANIZATION }}/hello-api-go

            Image Name: `${{ steps.docker_build.outputs.tag }}`

            Use `docker run --rm ${{ steps.docker_build.outputs.tag }}` to run it
